apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:eDBdQ+UchXFMqTgHM+uaYJ8iStulLJExtKDS5I408SvV0OuhmqZBZH75XNn27Wv0FUCV6ZimsGe0Z2448pjC2eqCpA6k2RrOXQOHIauDbv3cjeHgPMY08m8RMwT86tkYMGWm4tn0Q2cOSa31E6siKW292y0v5djuP7U+8+ou2wA7yWowlXc5p5wM3k1HyBpBxlmSlDqbCsX6IcBIQno8+nLV6UT8/qZPlZk97SP6V/rXDUWimP6BrnmIZwflqR61eKRLFfJZ8uP1QMIsIE19xaywo5jxeG2efg88lWuc2wvx9coxkNHM349l+co=,iv:JtizbHvs9ySw9q7cuewORJqFLJOTY5HLqCXCoD1R04s=,tag:WJt40GprYeqvJZBWI4ClmA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared-nwp-mtls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15q49wp6ljn007uqrxvpzyes20tumx4e6xej6ksfvfaehvfmmrd4szfaf66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNTdNNG5Zdm8vamN1ZzJO
            a0NaUGhyeXdkL3BYUjE5eXE3S0dVWTV3aVE4ClRjZkVsSzVxOWpPYmhYeWtUeXFF
            V0w1RFduQXBZYVA5Q1NEa2UrWU1uZDQKLS0tIGQxNDd4SllNZjhFQ09uN2ljcGcw
            cnZIRVlnUk5kRGRwemFIRjg3TUVqRlUKolrjPTBLuhPvmOOfIQtyqlenIYDoMphp
            LT3q7lkVPSAOQZkopGR1cHuR50WQ4i84weUofzXml8LTJzK0ieM5Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T23:36:44Z"
    mac: ENC[AES256_GCM,data:uouRX35rfSg45WQ/Dd9GRSu0KfktQsb/Sz/sPA+CIdM0UwO/OWSYJNdoRATp32kaWB0y5HJjkzgeKg4TAiK/OpuH+fhsvvI1xgE3nhIRNs1X/KU/rcbj6XHl4AjQywGcyHDUclMISk5GhEhZ/1eKp2y1bH9vJ9E1DeVAVxRsrek=,iv:XWOyDOhPSk554mt6Zo8yTzKhZGXz3UNOb5wW2oFgfGY=,tag:s2Vux0hif7VeZe8NSoqWbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
