apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: herowars
  namespace: herowars
  labels:
    nwarila.io/deploy-repo: "true"
spec:
  interval: 10m
  path: ./kubernetes/overlays/talos-cluster
  prune: true
  wait: true
  timeout: 10m
  targetNamespace: herowars
  serviceAccountName: deploy-reconciler
  sourceRef:
    kind: GitRepository
    name: herowars
