apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-auth-placeholder
  namespace: tenant-placeholder
spec:
  vaultAuthRef: vault-secrets-operator/org-pull-placeholder
  mount: secret
  type: kv-v2
  path: platform/org-pull/placeholder/gitops-source-auth
  refreshAfter: 1h
  destination:
    name: app-auth-placeholder
    create: true
    overwrite: true
    type: Opaque
