apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: app-auth-placeholder
  namespace: tenant-placeholder
spec:
  vaultAuthRef: vault-secrets-operator/tenant
  mount: secret
  type: kv-v2
  path: tenant-placeholder/provisioned/source-auth
  refreshAfter: 10m
  destination:
    name: app-auth-placeholder
    create: true
    overwrite: true
    type: Opaque
