apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - protect-tenant-label.yaml
  - protect-repo-sync-namespace.yaml
  - protect-source-minter.yaml
  - protect-vault-client-serviceaccount.yaml
  - protect-live-vault-config.yaml
  - restrict-vso-org-pull-secrets.yaml
  - protect-dr-validate-boundary.yaml
  - verify-image-signatures.yaml
  - verify-image-signatures-enforced.yaml
  - ivp-verify-first-party-nwarila.yaml
  - ivp-verify-first-party-nwarila-platform.yaml
  - ivp-verify-first-party-hwg.yaml
