apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deploy-vault
  namespace: deploy-vault
  labels:
    nwarila.io/deploy-repo: "true"
spec:
  interval: 5m
  ref:
    commit: d8de8588e11d5c7aa7a2e14f74782859634b7192
  url: https://github.com/nwarila-platform/deploy-vault.git
