apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: deploy-vault
  namespace: deploy-vault
  labels:
    nwarila.io/deploy-repo: "true"
spec:
  interval: 5m
  ref:
    commit: 81682df2a35ee309ccca828a180119fcaac03555
  url: https://github.com/nwarila-platform/deploy-vault.git
