apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: deploy-vault
  namespace: deploy-vault
  labels:
    nwarila.io/deploy-repo: "true"
spec:
  interval: 10m
  path: ./kubernetes/overlays/talos-cluster
  prune: false
  deletionPolicy: Orphan
  wait: true
  timeout: 10m
  targetNamespace: deploy-vault
  serviceAccountName: deploy-reconciler
  sourceRef:
    kind: GitRepository
    name: deploy-vault
  patches:
    - target:
        kind: StatefulSet
        name: vault
      patch: |-
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: vault
          annotations:
            kustomize.toolkit.fluxcd.io/prune: disabled
    - target:
        kind: Service
        name: vault
      patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: vault
          annotations:
            kustomize.toolkit.fluxcd.io/prune: disabled
    - target:
        kind: Service
        name: vault-internal
      patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: vault-internal
          annotations:
            kustomize.toolkit.fluxcd.io/prune: disabled
    - target:
        kind: ConfigMap
        name: vault-config
      patch: |-
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: vault-config
          annotations:
            kustomize.toolkit.fluxcd.io/prune: disabled
