apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-source-rotator-egress
  namespace: source-rotator
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: source-rotator
      app.kubernetes.io/component: source-token-minter
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
        - kube-apiserver
    - toServices:
        - k8sService:
            serviceName: vault
            namespace: deploy-vault
      toPorts:
        - ports:
            - port: "8200"
              protocol: TCP
    - toFQDNs:
        - matchName: api.github.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP