apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: source-rotator-hwg
  labels:
    app.kubernetes.io/name: source-rotator
    app.kubernetes.io/component: source-token-minter
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list