apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ciliumnetworkpolicy.yaml
  - configmap.yaml
  - vault-ingress.yaml
  # hwg (the-hero-wars-guys)
  - serviceaccount-hwg.yaml
  - clusterrole-hwg.yaml
  - clusterrolebinding-hwg.yaml
  - cronjob-hwg.yaml
  # nwp (nwarila-platform)
  - serviceaccount-nwp.yaml
  - clusterrole-nwp.yaml
  - clusterrolebinding-nwp.yaml
  - cronjob-nwp.yaml
