apiVersion: v1
kind: ServiceAccount
metadata:
  name: source-rotator-nwp
  namespace: source-rotator
  labels:
    app.kubernetes.io/name: source-rotator
    app.kubernetes.io/component: source-token-minter
automountServiceAccountToken: true
