# OCI HelmRepository colocated with the runner scale set HelmRelease.
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: arc-runners
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/actions/actions-runner-controller-charts
