apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nwarila-runner-registrar.sops.yaml
  - nwarila-runner-registrar-repo-sync.sops.yaml
  - nwarila-repo-sync-app-key.sops.yaml
  - hwg-arc-github-app.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - helmrelease-hwg.yaml
  - helmrepository-repo-sync.yaml
  - helmrelease-repo-sync.yaml
