apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-orchestrator
  namespace: dr-validate
  labels:
    app.kubernetes.io/name: vault-restore-validator
    app.kubernetes.io/component: orchestrator
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-generate-root
  namespace: dr-validate
  labels:
    app.kubernetes.io/name: vault-restore-validator
    app.kubernetes.io/component: recovery-quorum
automountServiceAccountToken: false
