#!/usr/bin/env bash
# =============================================================================
# onboard-tenant.sh - Generate a hardened tenant namespace envelope.
#
# Usage:
#   scripts/onboard-tenant.sh deploy-myapp [true|false]
#
# The second argument controls whether the Gateway ingress NetworkPolicy from
# the template is included. The script is intentionally repo-local and
# deterministic so GitHub Actions can open a reviewable PR instead of applying
# anything directly to the cluster.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

TENANT="${1:-}"
INCLUDE_GATEWAY="${2:-true}"

TEMPLATE_DIR="${TENANT_TEMPLATE_DIR:-${ROOT_DIR}/clusters/talos-cluster/tenants/_template}"
TENANTS_DIR="${TENANT_OUTPUT_ROOT:-${ROOT_DIR}/clusters/talos-cluster/tenants}"
TENANTS_KUSTOMIZATION="${TENANT_KUSTOMIZATION:-${TENANTS_DIR}/kustomization.yaml}"
GITIGNORE_PATH="${TENANT_GITIGNORE:-${ROOT_DIR}/.gitignore}"

usage() {
    echo "Usage: $0 deploy-name [true|false]" >&2
}

if [[ -z "${TENANT}" ]]; then
    usage
    exit 2
fi

if ! [[ "${TENANT}" =~ ^deploy-[a-z0-9]([-a-z0-9]*[a-z0-9])?$ ]]; then
    echo "ERROR: tenant must match ^deploy-[a-z0-9]([-a-z0-9]*[a-z0-9])?$" >&2
    exit 1
fi

case "${INCLUDE_GATEWAY}" in
    true|false) ;;
    *)
        echo "ERROR: include-gateway must be 'true' or 'false'" >&2
        exit 1
        ;;
esac

if [[ ! -d "${TEMPLATE_DIR}" ]]; then
    echo "ERROR: template directory not found: ${TEMPLATE_DIR}" >&2
    exit 1
fi
if [[ ! -f "${TENANTS_KUSTOMIZATION}" ]]; then
    echo "ERROR: tenants kustomization not found: ${TENANTS_KUSTOMIZATION}" >&2
    exit 1
fi
if [[ ! -f "${GITIGNORE_PATH}" ]]; then
    echo "ERROR: .gitignore not found: ${GITIGNORE_PATH}" >&2
    exit 1
fi

TENANT_DIR="${TENANTS_DIR}/${TENANT}"
if [[ -e "${TENANT_DIR}" ]]; then
    echo "ERROR: tenant directory already exists: ${TENANT_DIR}" >&2
    exit 1
fi

mkdir -p "${TENANT_DIR}"

render_template() {
    local source="$1"
    local target="$2"
    sed "s/__TENANT_NAMESPACE__/${TENANT}/g" "${source}" > "${target}"
}

render_template "${TEMPLATE_DIR}/namespace.yaml.tmpl" "${TENANT_DIR}/namespace.yaml"
render_template "${TEMPLATE_DIR}/networkpolicy-default-deny.yaml.tmpl" "${TENANT_DIR}/networkpolicy-default-deny.yaml"
render_template "${TEMPLATE_DIR}/networkpolicy-allow-dns.yaml.tmpl" "${TENANT_DIR}/networkpolicy-allow-dns.yaml"
if [[ "${INCLUDE_GATEWAY}" == "true" ]]; then
    render_template "${TEMPLATE_DIR}/networkpolicy-allow-gateway-ingress.yaml.tmpl" "${TENANT_DIR}/networkpolicy-allow-gateway-ingress.yaml"
fi

{
    echo "# Generated by scripts/onboard-tenant.sh."
    echo "apiVersion: kustomize.config.k8s.io/v1beta1"
    echo "kind: Kustomization"
    echo "resources:"
    echo "  - namespace.yaml"
    echo "  - networkpolicy-default-deny.yaml"
    echo "  - networkpolicy-allow-dns.yaml"
    if [[ "${INCLUDE_GATEWAY}" == "true" ]]; then
        echo "  - networkpolicy-allow-gateway-ingress.yaml"
    fi
} > "${TENANT_DIR}/kustomization.yaml"

update_tenants_kustomization() {
    local tmp
    tmp="$(mktemp)"

    {
        echo "# Kustomize index for onboarded tenant security envelopes."
        echo "#"
        echo "# Tenant directories are added here by .github/workflows/onboard-tenant.yaml."
        echo "apiVersion: kustomize.config.k8s.io/v1beta1"
        echo "kind: Kustomization"
        echo "resources:"
        {
            grep -E '^  - [a-z0-9][a-z0-9-]*$' "${TENANTS_KUSTOMIZATION}" | sed 's/^  - //' || true
            echo "${TENANT}"
        } | sort -u | sed 's/^/  - /'
    } > "${tmp}"

    mv "${tmp}" "${TENANTS_KUSTOMIZATION}"
}

append_gitignore_allowlist() {
    local line
    local lines=(
        "!/clusters/talos-cluster/tenants/${TENANT}/"
        "!/clusters/talos-cluster/tenants/${TENANT}/kustomization.yaml"
        "!/clusters/talos-cluster/tenants/${TENANT}/namespace.yaml"
        "!/clusters/talos-cluster/tenants/${TENANT}/networkpolicy-default-deny.yaml"
        "!/clusters/talos-cluster/tenants/${TENANT}/networkpolicy-allow-dns.yaml"
    )
    if [[ "${INCLUDE_GATEWAY}" == "true" ]]; then
        lines+=("!/clusters/talos-cluster/tenants/${TENANT}/networkpolicy-allow-gateway-ingress.yaml")
    fi

    {
        echo ""
        echo "# -- Tenant: ${TENANT} --------------------------------------------------------"
        for line in "${lines[@]}"; do
            echo "${line}"
        done
    } >> "${GITIGNORE_PATH}"
}

update_tenants_kustomization
append_gitignore_allowlist

echo "Generated tenant envelope: ${TENANT_DIR}"
