#!/usr/bin/env python3
"""Render the secret-free expected state consumed by the talos-drift CronJob."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


CONFIG_ENV = Path("cluster/config.env")
EXPECTED_ENV = Path("clusters/talos-cluster/apps/talos-drift/expected.env")


def parse_config_env(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in text.splitlines():
        match = re.match(r'^([A-Z0-9_]+)="([^"]*)"$', line.strip())
        if match:
            values[match.group(1)] = match.group(2)
    return values


def parse_nodes(value: str) -> list[tuple[str, str]]:
    nodes: list[tuple[str, str]] = []
    for part in value.split():
        if ":" not in part:
            raise ValueError(f"invalid node entry {part!r}")
        name, ip = part.split(":", 1)
        nodes.append((name, ip))
    return nodes


def render(values: dict[str, str]) -> str:
    required = ["CLUSTER_NAME", "KUBERNETES_VERSION", "TALOS_VERSION", "CP_NODES", "WORKER_NODES"]
    missing = [name for name in required if not values.get(name)]
    if missing:
        raise ValueError(f"missing required config.env values: {', '.join(missing)}")

    nodes = parse_nodes(values["CP_NODES"]) + parse_nodes(values["WORKER_NODES"])
    expected_nodes = ",".join(f"{name}={ip}" for name, ip in nodes)
    talos_nodes = ",".join(ip for _, ip in nodes)
    lines = [
        "# Generated by scripts/render-talos-drift-expected.py. Do not edit by hand.",
        f"CLUSTER_NAME={values['CLUSTER_NAME']}",
        f"KUBERNETES_VERSION={values['KUBERNETES_VERSION']}",
        f"TALOS_VERSION={values['TALOS_VERSION']}",
        f"EXPECTED_NODES={expected_nodes}",
        f"TALOS_NODES={talos_nodes}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if expected.env is stale")
    args = parser.parse_args()

    rendered = render(parse_config_env(CONFIG_ENV.read_text(encoding="utf-8")))
    if args.check:
        current = EXPECTED_ENV.read_text(encoding="utf-8").replace("\r\n", "\n")
        if current != rendered:
            print(f"{EXPECTED_ENV} is stale; run scripts/render-talos-drift-expected.py", file=sys.stderr)
            return 1
        print(f"{EXPECTED_ENV} matches {CONFIG_ENV}")
        return 0

    EXPECTED_ENV.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {EXPECTED_ENV}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
