apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-raft-snapshots
  namespace: dr-backup
  labels:
    app.kubernetes.io/name: dr-backup
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-vault-snapshot
  resources:
    requests:
      storage: 2Gi
