apiVersion: v1
kind: ServiceAccount
metadata:
  name: dr-backup
  namespace: dr-backup
  labels:
    app.kubernetes.io/name: dr-backup
    app.kubernetes.io/component: backup
automountServiceAccountToken: false
