apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-reconciler
  namespace: deploy-vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-reconciler
  namespace: deploy-vault
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - pods
      - pods/log
      - secrets
      - serviceaccounts
      - services
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources:
      - controllerrevisions
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["*"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-reconciler
  namespace: deploy-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-reconciler
subjects:
  - kind: ServiceAccount
    name: deploy-reconciler
    namespace: deploy-vault
