apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - serviceaccount-vault.yaml
  - vault-ca-secret.yaml
  - networkpolicy-default-deny.yaml
  - ciliumnetworkpolicy-egress.yaml
  - ciliumnetworkpolicy-webhook-ingress.yaml
