apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared-hwg
type: Opaque
data:
    credentials.json: ENC[AES256_GCM,data:a3UjvsKFklu6nX6ZInHsrwuvEKuwE31mtLPBnjo6rHT32ciKy9vNnCKwqf2V/rFI0M+X+cN3bMTqOY6TFc2GJDX5TFX+kc+geNOPfz9yF+Yr3IQu+llupetBFnoyumXqCMVqdYN4OWGY+HC1+an627BGLsq/xdZ+MECMJC75wt3xDD7lfsxOmNiWKamshWMfrE6SdmdGjc1pebmfq1UBA20bjIQZtwUNwDP1jsJ50QAiDhQlCOZdqB/WF6MxNo49rz2m9r/2/JIUot1ZulTlxEUcgz726yPtKyjq6R+FzxqF6bvegfgqZregYl0=,iv:XK/Tsy4QLyO4PZhZpUBCHp1U0Pnyj+xZUvPB0KDrINw=,tag:OIHq63fhqb6QaGVS4KnkZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15q49wp6ljn007uqrxvpzyes20tumx4e6xej6ksfvfaehvfmmrd4szfaf66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRFJRRlNwcmRZdWlKclk2
            SXNLaUI2ZUM3dDdVWjlNQVRVZUZ2azFPbmhnCk1BcmJhYi9MOGlDNktkbnJnb01D
            UzlMS1Y4bDQ0MUZSc1dWMnRDRklzUm8KLS0tIFRDbUplbmpyejQwSlZpaE1LeXJm
            VlJtR2U2Ym1lVERWWjJlelljUjVLL0EKlWCKUs61G+4uQNggLSTEI/PwCRITzMcP
            SsWRREuhj1rzYGHY7Pyin2osX6wwfR29hPZFasIX/DAMJuYYgBNjUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T16:31:52Z"
    mac: ENC[AES256_GCM,data:qxJi/BPnD1ecOm1ay1NOPKf5F753Z8lAxegDrbpTIopJzQLKftPTpf6VOiIJ0kU9p1ZKlnB2MblgRi9gHFFszNDtZluUx10u6Rn8VnrjFEqgh9W37oNZ111TkIlVAOwuUCWkIQ8EQrSVlhfTNP2KYizmclvwMjTTxqw9HV6ab3s=,iv:19uJphHs5XIFWqDZM/oENsW+XHi0o/lmPn+87Dte8hk=,tag:6QLPDzwDm5ZVPFCJPO7ajA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
