apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: hwg-herowars-engine-porter
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MXh3U0F982L2M9QgjJG64L7jYAJi9Mf4z/+1cbu+05OOcHkwUl5S0rJBZ/TtM32kjL35c2/VMLAJ00jcMQix4IO6PFMUN16A5aOAOBfWkmW6K5tCuZb69BGjp93AZEIhXvKefgphpZtdRNRF70rOoFgZU8IgXfR6kLkqy4hSaU/NjA+nU/HrDa4Fd9VAt1c61oTAWkMqkAyqGW4iLpe2YjHGgxQrhp7mJua4zoX+F8rsT3PWIn1+mu0GjwUHCNJxOdPEuenIcAcsbuEaaovFnmz8xLUq7bY+xueq3fRriBsMwzE9cVI+u5khUsisHEB5qEUkN0jEew/r3N7hsdASYA==,iv:VpuZQJF1TDYKkap7zaQOYVZmToHar2URKH59xKABwI8=,tag:sRWu4xDVWp4lFoKMG3y8yQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cmVPR0pWU1NJaisxSERp
            SEN3clV3RTM5MlUxQ3ZrY3I3KzFCV2RIYkg0CnJHem5ZVXdqUGs2M3Q1RXJFaXM5
            ZGFsdmY0Y0RqLzI1UnVheGIvMWRkb3MKLS0tIHlHY200QXlrQmR4NDBTVlN6TnlF
            YnE0bWdoWTRmbkJWU3Z6ZXBNdE8rd1kK+0aZCljCLjV3m6VrO8l2J+GfflUVfBlz
            JZwpwsn0j5z3ADRscsgNlLA4Nkt1ZFz+MpSBC7HCl+xKjQoDjnlTCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q49wp6ljn007uqrxvpzyes20tumx4e6xej6ksfvfaehvfmmrd4szfaf66
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T01:59:00Z"
    mac: ENC[AES256_GCM,data:XHoVrFIbhWPg8/jjQ0vwP54/T5kD/uH0AT1Z8APIrmpZNxA4HRorDSY6IFh8iUkIDpZDqtnYRPedfQ12Ay6e+joCRSkLT5GJR8a3iQuzK20cKuSRo6SrVOYHVQwXa+IPf8bV/9Q8woOA8ByqeQO7gQw3Jko5xpQZ7/kcHk1AQNY=,iv:CbaEHXNjCYBYhCzptOH8Uh4U2i5gfJGur88bY+cntss=,tag:zUgAT+HsrwZOg/SNtuXkmA==,type:str]
    version: 3.13.1
