apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: herowars-gitops-source-auth
spec:
  vaultAuthRef: vault-secrets-operator/org-pull-hwg
  mount: secret
  type: kv-v2
  path: platform/org-pull/hwg/gitops-source-auth
  refreshAfter: 1h
  destination:
    name: herowars-gitops-source-auth
    create: true
    overwrite: true
    type: Opaque