apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ghcr-pull
spec:
  vaultAuthRef: vault-secrets-operator/org-pull-hwg
  mount: secret
  type: kv-v2
  path: platform/org-pull/hwg/ghcr-pull
  refreshAfter: 1h
  destination:
    name: ghcr-pull
    create: true
    overwrite: true
    type: kubernetes.io/dockerconfigjson