apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - talos-reader-talosconfig.sops.yaml
  - cronjob.yaml
configMapGenerator:
  - name: talos-drift-expected
    envs:
      - expected.env
  - name: talos-drift-check
    files:
      - check.py
generatorOptions:
  disableNameSuffixHash: true
