apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tunnel-credentials.sops.yaml
  - configmap.yaml
  - deployment.yaml
  - poddisruptionbudget.yaml
  - ciliumnetworkpolicy.yaml
  - networkpolicy-default-deny.yaml
