apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared-nwp-public
  namespace: cloudflared-nwp-public
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: nwp-public
