apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Brfiiwu++1XCRJBa3TO+VrToDnUNDOwHPqC5Ntb7S7bWr8vQ0NPYo8D1n7z45Yv6Z24UNdbuMww+wSKP0l1Gys+cG4oNANU/6qOmg6DOeGYva9pY00gRJhR5XIe016EJCSaD3sm8M3gwGecWXF+RJeDH+5KO/VFFQmoYm0KTssFYneN9D2f58bVUPLvkk0/VCtoGfHhIQRGtVU/NwYUkoHsSEradrcXz6Sf7Ozra8rp9oKkXm1lFq6JS4IFUOfZqUAVEyvEpM90505jGay2NKmcEZEe5Chi3zbR2jr/Kmnmb6cX2xLpJ07H9WSc=,iv:2Mf8h6d4E9GujgT2rXNaHEgVmasO7p+E96LKJaDvQfE=,tag:Q1iVpNmW6rzhqmSMoyoSZQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflared-nwp-public
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15q49wp6ljn007uqrxvpzyes20tumx4e6xej6ksfvfaehvfmmrd4szfaf66
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNkFGM3dQMEZoMkljQTNX
            OHF2YzJWZVk3d2M5eGJjdG9HMjZGeTQ1TDFvCkhYK3dxOGF3SG4xN01YY3dZb1JF
            WlIycnpKbGhoOWhKdGJuTkxteE5uWmMKLS0tIGw3VEtQUlk3NyttaUZWYXhUUGx1
            bjdVTXBUY2FxVGtpTFd2L1k1Q3FiczgK+8mqI3Y0Ti9pyqdfMLtwCHmK0OFJdFlQ
            DIL7izVczJA3dJKKcgv6Imrj8xuJl3WtMGEzla97rnwwp/eUI2Kscg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T23:36:44Z"
    mac: ENC[AES256_GCM,data:X/46RafQjwbjsbMDoReiGtQwfb+7XZuaiJ2UtgGfvCvaavRVcJw/wYLoYGMETKtN6LLKq4vlB38I7GsVD5FPz5KAd3QT5pV0TQN60fHbcO/XhlmlhhlgVQ6E/f8mDHXisVTyIpUOoQzwDDQWqHLLZdx9nP6keAHUn1QqBNnhJD8=,iv:jyUYTKMWsZCVV4JqD3XB6/2qeaD+WTPYxnBP87FtX5U=,tag:PHJkJyPwmU3w9cayw4bIKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
