name: Template Sync

on:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: template-sync
  cancel-in-progress: false

jobs:
  sync:
    uses: NWarila/terraform-template/.github/workflows/reusable-template-sync.yaml@7b7e2eb931432ffde9de8d56bf013b28f40b2753
    with:
      template_ref: 7b7e2eb931432ffde9de8d56bf013b28f40b2753
