apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source-namespace.yaml
  - target-namespace.yaml
  - source-secret.sops.yaml
  - background-controller-secret-rbac.yaml
  - kustomization-policy.yaml
