apiVersion: v1
kind: Secret
metadata:
    name: sops-clone-validation-source
    namespace: kyverno-clone-validation-source
    labels:
        app.kubernetes.io/name: kyverno-clone-validation
        app.kubernetes.io/part-of: kyverno-clone-validation
        validation.nwarila.io/sops-clone-source: "true"
    annotations:
        validation.nwarila.io/throwaway: "true"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:q6aPnUIXczNDXp+oAeH3JhsMZUU4,iv:Qidkwg0pVTVmXRNetUy//6wmtTR9R08RallyE+YS5VE=,tag:PMHuCLWofci0MTb6jX1rfw==,type:str]
    password: ENC[AES256_GCM,data:F/BE1sRh+dtDz7+NsIJobcolp+CHDMARqw==,iv:VN31hWMwKi3M0ovAbrJYqaiP0pDPFsOUgZtYJMVWuP4=,tag:dS0LNHr8Ip1NRLNAjCbo6g==,type:str]
    purpose: ENC[AES256_GCM,data:9gRmDVN6PrluWO17iBBHD+PMvfEK3hnYQqdwYAs=,iv:bdvzt+UtPuJ1DrN+/yRAQsgEzW9uFinVPW2jYTGVu7E=,tag:j+YY7Kl1BXd0cSLhbzjs3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUzBiZFdKeDRJNDZyTXZ0
            TUVEMmV3Tjh0akwvVzBjOFBpVkR0OWFnREJzCnVyRVhaMExDTzJwYzZySlVhTVZt
            eHpoSDloSzc5bjd1R1lmQUpPYkEwUW8KLS0tIGsvWU00RlNrblFhVGJhSEllSGFr
            RTBBNUMvd0tTeE1ZMXBZNGNFN1J0UXMKZBXhAbMt+9I+lhqBXj9ME1HKQ2V/vCuU
            QqK7co6YuW9uc/8TLY2zTKP8UpZ2KwGW5yX+HPcOKxAUAVY4qs4kPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15q49wp6ljn007uqrxvpzyes20tumx4e6xej6ksfvfaehvfmmrd4szfaf66
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T16:08:00Z"
    mac: ENC[AES256_GCM,data:7Ri0pZ4fax7EI85XWFh8DsfXwZlQ4LlkzAUPNuJ/Y6qCMGfbzapPCSsLlimWvHX90vq9lr+2SXmlqOjj2EesHI9HKdv+i7ZsFw74Bll2tmNyHMoVjJJ/3efncyMgjas5/d2c7tJJBYiS1zMPmI6NjVR8VaRdPVcgpiH9xABswOA=,iv:T6xVSLpeOMu4C2Su/VtgJCZPqHGSt+8N7PUtM2cnI/k=,tag:ejh4FNYZ+Oyhza06c6EouQ==,type:str]
    version: 3.13.1
