apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-clone-validation-target
  labels:
    app.kubernetes.io/name: kyverno-clone-validation
    app.kubernetes.io/part-of: kyverno-clone-validation
    validation.nwarila.io/sops-clone-test: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
